services:
  - type: web
    name: mctiers
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend && npm install --prefix backend && npm run build --prefix backend
    startCommand: node backend/dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        generateValue: false
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
